version: '3.8'

services:
  backend:
    build:
      context: ./ai-resume-parser-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./ai-resume-parser-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
